### PR TITLE
Update sensor.py

### PR DESCRIPTION
**Pull request by lloydbayley**
Add yesterday_rain to sensor.py

### CODE REVIEW

**Comment by pilotak** [comment]
Thanks for submitting the code again (and contributing for the first time to the open source world). The code look good to me, the only thing is if you could also updade both `README.md` and `info.md` to include newly added "yesterday_rain" so people could see that is exists without looking into the code.

**Comment by lloydbayley** [comment]
My apologies. I did wonder if that was up to me to do or you, as the author.
What is the best way to do that? Do I update the files and submit another pull request or do I close this one and do it all again?

 Thanks for being kind about my first submission 😊
Cheers,

Lloyd Bayley
Berowra PC Services
lloyd@berowrapc.com<mailto:lloyd@berowrapc.com>
P.O. Box 270
Berowra Heights NSW 2082
Direct:     (02) 9456-0292
Mobile:    0411-541-007
Web:       www.berowrapc.com<blocked::http://www.berowrapc.com>

**Comment by pilotak** [comment]
All you have to do is update those two files and push to your forked repo as you did with `sensor.py` or if you did this via github.com GUI open the forked repo, click on the file -> click on the pencil to edit and hit save. It will be saved in your repo and linked to this PR as well (as long as it's the same branch)

**Comment by lloydbayley** [comment]
Thank you so much. Will give it a go!

Cheers,



Lloyd Bayley
Berowra PC Services
lloyd@berowrapc.com<mailto:lloyd@berowrapc.com>
P.O. Box 270
Berowra Heights NSW 2082
Direct:     (02) 9456-0292
Mobile:    0411-541-007
Web:       www.berowrapc.com<blocked::http://www.berowrapc.com>

**Comment by pilotak** [comment]
perfect, I had tested it

**Comment by lloydbayley** [comment]
Thank you SO much for your patience. I’m excited about my first contrib.

Best wishes to you.

Cheers,

Lloyd Bayley
Berowra PC Services
lloyd@berowrapc.com<mailto:lloyd@berowrapc.com>
P.O. Box 270
Berowra Heights NSW 2082
Direct:     (02) 9456-0292
Mobile:    0411-541-007
Web:       www.berowrapc.com<blocked::http://www.berowrapc.com>

**Pull request merged**
