### PR TITLE
added Station and Date from clientraw.txt information

### PR DESCRIPTION
**Pull request by martinezpenya**
Hi! I've noticed you've moved old project, so I added your extension from HACS without problem, but in the previous project I've added Station and Date from clientraw.txt to retrieve info about the station and last date/time update.
I'll hope you like to add this to your project.
Thank you for your work.

### CODE REVIEW

**Comment by pilotak** [comment]
Could you please make a docu in `README.md` and `info.md` so other people know that it's available

**Comment by martinezpenya** [comment]
> Could you please make a docu in `README.md` and `info.md` so other people know that it's available

I think I've done it now.
Can you check, please?

**Comment by pilotak** [comment]
Perfect, however there is a PEP8 validation fail
https://github.com/pilotak/homeassistant-clientraw/runs/5618530623?check_suite_focus=true

**Comment by martinezpenya** [comment]
> Perfect, however there is a PEP8 validation fail https://github.com/pilotak/homeassistant-clientraw/runs/5618530623?check_suite_focus=true

I think I've solved the two problems on PEP8 (i'm new on this).
How I can check another time now?

**Comment by pilotak** [comment]
you can see it here at the bottom, i have approved the Action to run

**Comment by martinezpenya** [comment]
> you can see it here at the bottom, i have approved the Action to run

Check now, please. The last line was not a pure empty new line.
Only you can run test, or can i?

**Comment by pilotak** [comment]
as a first time contributor (this repo), i need to approve it all the time until success

**Comment by martinezpenya** [comment]
> as a first time contributor (this repo), i need to approve it all the time until success

Ok, thank you.

**Comment by pilotak** [comment]
Done, thank you very much for the contribution

**Pull request merged**
