### PR TITLE
Add Solar Irradiation & UV index

### LINKED ISSUE #27: Add solar & UV
what if clientraw parser included solar and uv sensors? Some of we have possibility to get our weather stations solar and  uv readings, so i woudl be nice to get that to HA

### PR DESCRIPTION
**Pull request by pilotak**
Fixes #27

### CODE REVIEW

**Review by systeemi — APPROVED** [review]

**Review by systeemi — APPROVED** [review]

**Review by systeemi — APPROVED** [review]

**Comment by systeemi** [comment]
Hello

Sorry its take a while, because i have to learn how to use github desktop and I have to make samba server to my HA. And now I have been tested clientraw parser. Now it parser mainly works  but there is issue in UV and solar readings. In HA i get error (target is not numeric) so this not get values. 

I am noob, sorry for that

I have the order wrong in config.yaml and now I get the solar value but UV value still get same error.

And solar reading jam.. if I start HA again, then it gets new reading. (edit: its not jam refrestime is 1hour)

**Comment by pilotak** [comment]
please post a log or screenshot of the log, i can't test it as i don't have a UV & solar

**Comment by systeemi** [comment]
> please post a log or screenshot of the log, i can't test it as i don't have a UV & solar

If I share my clientraw file address? Can you give email address?

**Comment by pilotak** [comment]
i would still prefer to see the log, i don't want to install you weather under mine... 

you can find the email under git commit, otherwise robots will pick this up if i make it public

**Comment by systeemi** [comment]
> i would still prefer to see the log, i don't want to install you weather under mine...
> 
> you can find the email under git commit, otherwise robots will pick this up if i make it public

I try to send you email. Where I find log what you want to see??
Solar readings works now. If I use config.yaml uv_index parser doesnt work anymore.

**Comment by pilotak** [comment]
https://www.home-assistant.io/integrations/system_log/

> Settings -> System -> Logs

**Comment by systeemi** [comment]
image

**Comment by systeemi** [comment]
image

When I include yaml uv_index

**Comment by systeemi** [comment]
image

**Comment by systeemi** [comment]
image

**Comment by systeemi** [comment]
This situation ios when configuration.yaml included uv_index

**Comment by pilotak** [comment]
perfect many thanks, please try it now

**Comment by systeemi** [comment]
YES! now we dont have errors and both values showing. 
Is here any support possibility?

**Comment by pilotak** [comment]
Glad it works, no there isn't any support, it would require me to set up accounts who know where... github sponsor is no available in my country. But it's nice you from you, I appreciate it.

**Pull request merged**
